ALTER TABLE cities
    ADD CONSTRAINT fk_teams FOREIGN KEY (id_teams) REFERENCES teams(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE cities
    ADD CONSTRAINT fk_positions FOREIGN KEY (id_positions) REFERENCES positions(id) ON UPDATE RESTRICT ON DELETE RESTRICT;