ALTER TABLE teams
    ADD CONSTRAINT fk_leagues FOREIGN KEY (id_leagues) REFERENCES leagues(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE teams
    ADD CONSTRAINT fk_stadiums FOREIGN KEY (id_stadiums) REFERENCES stadiums(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE teams
    ADD CONSTRAINT fk_cities FOREIGN KEY (id_cities) REFERENCES cities(id) ON UPDATE RESTRICT ON DELETE RESTRICT;