ALTER TABLE city
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE city
    ADD CONSTRAINT fk_league FOREIGN KEY (id_league) REFERENCES league(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
