ALTER TABLE coach
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE coach
    ADD CONSTRAINT fk_team FOREIGN KEY (id_team) REFERENCES team(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE coach
    ADD CONSTRAINT fk_position FOREIGN KEY (id_position) REFERENCES position(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE coach
    ADD CONSTRAINT fk_player FOREIGN KEY (id_player_on_training) REFERENCES player(id) ON UPDATE RESTRICT ON DELETE RESTRICT;