ALTER TABLE market
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE market
    ADD CONSTRAINT fk_start_day FOREIGN KEY (id_start_day) REFERENCES day(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE market
    ADD CONSTRAINT fk_finish_day FOREIGN KEY (id_finish_day) REFERENCES day(id) ON UPDATE RESTRICT ON DELETE RESTRICT;