ALTER TABLE player
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE player
    ADD CONSTRAINT fk_position FOREIGN KEY (id_position) REFERENCES position(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE player
    ADD CONSTRAINT fk_team FOREIGN KEY (id_team) REFERENCES team(id) ON UPDATE RESTRICT ON DELETE RESTRICT;