ALTER TABLE stadium
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE stadium
    ADD CONSTRAINT fk_team FOREIGN KEY (id_team) REFERENCES team(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE stadium
    ADD CONSTRAINT fk_league FOREIGN KEY (id_league) REFERENCES league(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE stadium
    ADD CONSTRAINT fk_city FOREIGN KEY (id_city) REFERENCES city(id) ON UPDATE RESTRICT ON DELETE RESTRICT;