ALTER TABLE team
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user_table(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE team
    ADD CONSTRAINT fk_league FOREIGN KEY (id_league) REFERENCES league(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE team
    ADD CONSTRAINT fk_stadium FOREIGN KEY (id_stadium) REFERENCES stadium(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE team
    ADD CONSTRAINT fk_city FOREIGN KEY (id_city) REFERENCES city(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE team
    ADD CONSTRAINT fk_head_coach FOREIGN KEY (id_head_coach) REFERENCES head_coach(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE team
    ADD CONSTRAINT fk_sponsor FOREIGN KEY (id_sponsor) REFERENCES sponsor(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE team
    ADD CONSTRAINT fk_placement FOREIGN KEY (id_placement) REFERENCES placement(id) ON UPDATE CASCADE ON DELETE RESTRICT;